FORMAT: 1A
HOST: https://target-ricardo.herokuapp.com/

#TARGET

Target test application

## Users Collection [/api/v1/users]

### Sign up [POST]

+ Request (application/json)
    + Attributes
        + user (Profile Creation, required)

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com

    + Attributes
        + user (Profile Response, required)

## Login [/api/v1/users/sign_in]

### Login [POST]

+ Request (application/json)

    + Body
    
            {
                "user":
                {
                    "email":    "test@test.com",
                    "password": "password"
                }
            }

+ Response 200 (application/json)
    + Headers

            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com


    + Attributes
        + user (Profile Response, required)

## Targets Collection [/api/v1/targets]

### Create target [POST]
+ Request (application/json)
    + Headers
            
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
    
    + Attributes
    
        + target (Target Request, required)
            
+ Response 200 (application/json)
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
            
    + Attributes
            
        + target (Target Response, required)

### Get Targets [GET]
+ Request (application/json)
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
            
+ Response 200
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
            
    + Attributes
        - targets (array[Target Response])

## Specific Target  [/api/v1/targets/:id]

### Show target [GET]
+ Request (application/json)
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com

+ Response 200
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
            
    + Attributes
        
        + target (Target Response, required)

### Destroy target [DELETE]
+ Request (application/json)
  + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com
            
+ Response 204
    + Headers
    
            access-token: sO2bm_Bpdyoo8r78jZ-fqg
            client:       QADgNCWRJj0LyRruqzYbBg
            expiry:       1535989794
            uid:          test@test.com

# Data Structures

## Profile Response (object)
+ uid:        test@test.com (string) - the provider identifier
+ id:         100 (number)
+ email:      test@test.com (string)
+ provider:   email (enum[string]) - it's the way the user logs in
+ created_at: 2017-02-23T13:54:33.283Z (string)
+ updated_at: 2018-08-20T15:26:25.950Z (string)

## Profile Creation (object)
+ email:                 test@test.com (string, required)
+ password:              12345678 (string, required)
+ password_confirmation: 12345678 (string, required)

## Target Request (object)
+ radius:   600 (number, required)
+ title:    title (string, required)
+ latitude: 34.90834 (number, required)
+ longitue: 56.2031514 (number, required)
+ topic: football, travel, politics, art, dating, music, movies, series, food (enum[string], required)

## Target Response (object)
+ id:       41 (number, required)
+ radius:   600 (number, required)
+ title:    title (string, required)
+ latitude: 34.90834 (number, required)
+ longitue: 56.2031514 (number, required)
+ topic: football, travel, politics, art, dating, music, movies, series, food (enum[string], required)
